name: tugas3_tpm
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/hitungku_logo.png
    - assets/logos/logo-hijau.png
    - assets/logos/logo-putih.png
    - assets/images/header_menu.jpg
    - assets/images/anggota1.jpg
    - assets/images/anggota2.jpg

fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Bold.ttf
